---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: fetch-tags
    image: alpine/git
    commands:
      - git fetch --tags

  - name: test
    image: golang:1.16.7
    volumes:
      - name: cache
        path: /go
    commands:
      - ./scripts/download-test-geoip
      - go get
      - go test -v ./...
      - go build ./...

  - name: goreleaser
    image: golang:1.16.7
    volumes:
      - name: cache
        path: /go
    commands:
      - ./scripts/run-goreleaser
      - echo Done
    when:
      ref:
        - refs/heads/main
        - refs/heads/drone-test
        - refs/tags/**
    depends_on: [test]

  - name: upload
    image: plugins/s3
    settings:
      access_key:
        from_secret: s3_access_key
      secret_key:
        from_secret: s3_secret_key
      bucket: geodns
      target: /builds/${DRONE_BUILD_NUMBER}
      source: dist/*
      strip_prefix: dist/
      endpoint: https://minio-ewr1.develooper.com/
      path_style: true
    depends_on: [goreleaser]

  - name: fury-publish
    image: golang:1.16.7
    environment:
      FURY_TOKEN:
        from_secret: fury_test_token
    commands:
      - ./scripts/fury-publish ntppool-test
    when:
      ref:
        - refs/heads/main
        - refs/heads/drone-test
        - refs/tags/**
    depends_on: [goreleaser]

volumes:
  - name: cache
    temp: {}

trigger:
  event:
    - push
    - tag
    - pull_request

---
kind: pipeline
type: kubernetes
name: publish-production

steps:
  - name: download
    image: golang:1.16.7
    commands:
      - ./scripts/download-release ${DRONE_BUILD_PARENT} dist/

  - name: fury-publish
    image: golang:1.16.7
    environment:
      FURY_TOKEN:
        from_secret: fury_token
    commands:
      - ./scripts/fury-publish ntppool
    depends_on: ["download"]

trigger:
  event:
    - promote
  target:
    - publish
---
kind: signature
hmac: 687f4bc1dfa9b493fed2838a5033619ea1d5a8cc7b1133dc16db6489552ea896

...
